export const projects = [
  {
    title: 'Youtube Clone',
    description: "A 2020's Replica of Youtubes Homepage with example search results page. Using React, Node.js, and deployed on Firebase. This project help me become better at styling\n",
      image: '/images/youtubeclone.png',
      tags: ['React', 'Node'],
    source: 'https://github.com/nrhymer23/youtube-clone',
    visit: 'https://clone-8ef48.web.app',
    id: 0,
  },
  {
    title: 'Google Clone',
    description:"A 2020's Replica of Google Homepage with Functional search results page. Using React, Node.js, and deployed on Firebase. Along with becoming more proficent using React Router I was able to integrate Googles search API successfully.\n",
    image:'/images/googleclone.png',
    tags: ['React', 'Node'],
    source: 'https://github.com/nrhymer23/react-google-clone',
    visit: 'https://clone-3e910.web.app',
    id: 1,
  },
  {
    title: 'Ultimate Chess',
    description:"Ultimate chess is a variation from the traditional chess. it was created in unity and objects programmed in C#. This project developed my ability to created interfaces & UI. It also introduced me to the application of AI\n",
    image:'/images/UC2.png',
    tags: ['C#', 'Unity'],
    source: 'https://github.com/nrhymer23/UltimateChess.git',
    visit: 'https://play.unity.com/mg/other/ultimatechessv4-app',
    id: 2,
  },
  {
    title: 'Weather App',
    description: "This small project help me get familar with the React framework. I worked with CSS styling and API integration. Optimized as a Progessive Web Application so the app can be downloaded right from chrome.\n",
    image: 'images/Weatherapp.png',
    tags: ['React',],
    source: 'https://github.com/nrhymer23/pwa-react-demo',
    visit: 'https://condescending-rosalind-b02f66.netlify.app/',
    id: 3,
  },
  {
    title: 'The VideoGame Store',
    description: "This This is a Shopping cart styled website created with the .Net Framework. It fully functional e-commerce template written in C# with database implementation.\n",
    image: 'images/vgs.png',
    tags: ['.Net'],
    source: 'https://github.com/nrhymer23/Videogamestore',
    visit: '',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2014, text: 'Started My Journey in the IT world', },
  { year: 2015, text: 'Worked as a freelance Tech', },
  { year: 2019, text: 'Graduated From Kennessaw With Computer Science Degree', },
  { year: 2020, text: 'Started GenzTech ', },
  {  },
];